import NAVIGATION_LINKS from "./NAVIGATION_LINKS";
import SEARCH_DETAIL from "./SEARCH_DETAILS";
import OPTIONS from "./OPTIONS";
import BUILDERS_DATA from "./BUILDERS_DATA";
import FOOTER_DROPDOWN_LINKS from "./FOOTER_DROPDOWN_LINKS";

export {
  NAVIGATION_LINKS,
  SEARCH_DETAIL,
  OPTIONS,
  BUILDERS_DATA,
  FOOTER_DROPDOWN_LINKS,
};
